"""add user id to tasks

Revision ID: 2faeb2a72898
Revises: 
Create Date: 2026-09-15 12:31:30.500911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faeb2a72898'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute(
        sa.text(
            'UPDATE user_tasks '
            'SET user_id = (SELECT id FROM "Users" ORDER BY id LIMIT 1) '
            'WHERE user_id IS NULL'
        )
    )
    op.execute(
        sa.text(
            'UPDATE user_tasks SET is_completed = FALSE '
            'WHERE is_completed IS NULL'
        )
    )
    op.alter_column('user_tasks', 'user_id', nullable=False)
    op.alter_column('user_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(
        'fk_user_tasks_user_id', 'user_tasks', 'Users', ['user_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_tasks_user_id', 'user_tasks', type_='foreignkey')
    op.alter_column('user_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user_tasks', 'user_id')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    # ### end Alembic commands ###
